######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 14 17:16:58 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /sw/include
LIBS += -lftd2xx ../lib/libgc.a

# Input
HEADERS += D2XX.h
SOURCES += D2XX.cpp PowerTap.cpp

