######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 14 17:16:58 2007
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /sw/include
LIBS += -lftd2xx ../lib/libgc.a
CONFIG += static

# Input
HEADERS += Device.h Serial.h D2XX.h PowerTap.h
SOURCES += Device.cpp Serial.cpp D2XX.cpp PowerTap.cpp main.cpp

