######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 14 16:49:39 2007
######################################################################

TEMPLATE = lib
TARGET = gc
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += static

# Input
HEADERS += pt.h
SOURCES += pt.cpp

