######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 15 11:51:10 2009
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
DEFINES += HAVE_CONFIG_H
CONFIG += staticlib

# Input
HEADERS += common.h config.h srmio.h srmio_config.h
SOURCES += srmdata.c srmfile.c srmpc.c
