#line 2 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/DataFilter_lex.cpp"
  #include <stdint.h>

#line 5 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/DataFilter_lex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer DataFilter_create_buffer
#define yy_delete_buffer DataFilter_delete_buffer
#define yy_scan_buffer DataFilter_scan_buffer
#define yy_scan_string DataFilter_scan_string
#define yy_scan_bytes DataFilter_scan_bytes
#define yy_init_buffer DataFilter_init_buffer
#define yy_flush_buffer DataFilter_flush_buffer
#define yy_load_buffer_state DataFilter_load_buffer_state
#define yy_switch_to_buffer DataFilter_switch_to_buffer
#define yypush_buffer_state DataFilterpush_buffer_state
#define yypop_buffer_state DataFilterpop_buffer_state
#define yyensure_buffer_stack DataFilterensure_buffer_stack
#define yy_flex_debug DataFilter_flex_debug
#define yyin DataFilterin
#define yyleng DataFilterleng
#define yylex DataFilterlex
#define yylineno DataFilterlineno
#define yyout DataFilterout
#define yyrestart DataFilterrestart
#define yytext DataFiltertext
#define yywrap DataFilterwrap
#define yyalloc DataFilteralloc
#define yyrealloc DataFilterrealloc
#define yyfree DataFilterfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define DataFilter_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer DataFilter_create_buffer
#endif

#ifdef yy_delete_buffer
#define DataFilter_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer DataFilter_delete_buffer
#endif

#ifdef yy_scan_buffer
#define DataFilter_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer DataFilter_scan_buffer
#endif

#ifdef yy_scan_string
#define DataFilter_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string DataFilter_scan_string
#endif

#ifdef yy_scan_bytes
#define DataFilter_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes DataFilter_scan_bytes
#endif

#ifdef yy_init_buffer
#define DataFilter_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer DataFilter_init_buffer
#endif

#ifdef yy_flush_buffer
#define DataFilter_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer DataFilter_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define DataFilter_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state DataFilter_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define DataFilter_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer DataFilter_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define DataFilterpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state DataFilterpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define DataFilterpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state DataFilterpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define DataFilterensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack DataFilterensure_buffer_stack
#endif

#ifdef yylex
#define DataFilterlex_ALREADY_DEFINED
#else
#define yylex DataFilterlex
#endif

#ifdef yyrestart
#define DataFilterrestart_ALREADY_DEFINED
#else
#define yyrestart DataFilterrestart
#endif

#ifdef yylex_init
#define DataFilterlex_init_ALREADY_DEFINED
#else
#define yylex_init DataFilterlex_init
#endif

#ifdef yylex_init_extra
#define DataFilterlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra DataFilterlex_init_extra
#endif

#ifdef yylex_destroy
#define DataFilterlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy DataFilterlex_destroy
#endif

#ifdef yyget_debug
#define DataFilterget_debug_ALREADY_DEFINED
#else
#define yyget_debug DataFilterget_debug
#endif

#ifdef yyset_debug
#define DataFilterset_debug_ALREADY_DEFINED
#else
#define yyset_debug DataFilterset_debug
#endif

#ifdef yyget_extra
#define DataFilterget_extra_ALREADY_DEFINED
#else
#define yyget_extra DataFilterget_extra
#endif

#ifdef yyset_extra
#define DataFilterset_extra_ALREADY_DEFINED
#else
#define yyset_extra DataFilterset_extra
#endif

#ifdef yyget_in
#define DataFilterget_in_ALREADY_DEFINED
#else
#define yyget_in DataFilterget_in
#endif

#ifdef yyset_in
#define DataFilterset_in_ALREADY_DEFINED
#else
#define yyset_in DataFilterset_in
#endif

#ifdef yyget_out
#define DataFilterget_out_ALREADY_DEFINED
#else
#define yyget_out DataFilterget_out
#endif

#ifdef yyset_out
#define DataFilterset_out_ALREADY_DEFINED
#else
#define yyset_out DataFilterset_out
#endif

#ifdef yyget_leng
#define DataFilterget_leng_ALREADY_DEFINED
#else
#define yyget_leng DataFilterget_leng
#endif

#ifdef yyget_text
#define DataFilterget_text_ALREADY_DEFINED
#else
#define yyget_text DataFilterget_text
#endif

#ifdef yyget_lineno
#define DataFilterget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno DataFilterget_lineno
#endif

#ifdef yyset_lineno
#define DataFilterset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno DataFilterset_lineno
#endif

#ifdef yywrap
#define DataFilterwrap_ALREADY_DEFINED
#else
#define yywrap DataFilterwrap
#endif

#ifdef yyalloc
#define DataFilteralloc_ALREADY_DEFINED
#else
#define yyalloc DataFilteralloc
#endif

#ifdef yyrealloc
#define DataFilterrealloc_ALREADY_DEFINED
#else
#define yyrealloc DataFilterrealloc
#endif

#ifdef yyfree
#define DataFilterfree_ALREADY_DEFINED
#else
#define yyfree DataFilterfree
#endif

#ifdef yytext
#define DataFiltertext_ALREADY_DEFINED
#else
#define yytext DataFiltertext
#endif

#ifdef yyleng
#define DataFilterleng_ALREADY_DEFINED
#else
#define yyleng DataFilterleng
#endif

#ifdef yyin
#define DataFilterin_ALREADY_DEFINED
#else
#define yyin DataFilterin
#endif

#ifdef yyout
#define DataFilterout_ALREADY_DEFINED
#else
#define yyout DataFilterout
#endif

#ifdef yy_flex_debug
#define DataFilter_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug DataFilter_flex_debug
#endif

#ifdef yylineno
#define DataFilterlineno_ALREADY_DEFINED
#else
#define yylineno DataFilterlineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define DataFilterwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[506] =
    {   0,
        0,    0,   63,   61,   60,   60,   61,    1,   61,   61,
       57,   55,   56,   61,   58,   26,    5,    3,    7,   61,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   59,   54,   54,   54,   54,   54,   54,   61,
        0,   28,    0,    1,    0,   22,   27,   53,    0,   26,
       53,   10,    6,    4,    8,    9,   53,   53,   53,   51,
       53,   53,   53,   53,   53,   25,   53,   53,   53,   50,
       53,   53,   53,   53,   53,   11,   50,   53,   24,   28,
        0,    0,    0,   27,   23,   53,   53,   53,   53,   53,
       53,   53,   53,   52,   19,   53,    0,    0,   53,   53,

       53,   53,   53,   53,    0,   27,   53,   18,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,    0,    0,
       53,   53,   53,   53,   53,   53,   53,   53,   12,   53,
        0,   53,   53,   21,   53,   53,    0,   53,   53,   53,
       53,   53,    0,    0,    0,   53,    0,   53,    0,   53,
        0,   53,    0,   13,    0,   53,   20,   53,   53,    0,
       53,    0,   53,   53,    0,    0,    0,    0,   53,    0,
       53,    0,   53,    0,   53,    0,    0,   53,   53,   53,
        0,   14,    0,   53,   53,    0,    0,   36,    0,    0,
       53,    0,   53,    0,   53,    0,   53,    0,    0,   53,

       17,   16,    0,    0,   53,   53,    0,   37,    0,    0,
       53,    0,   53,    0,   53,    0,   53,    0,    0,    0,
        0,   53,    0,    0,   53,   53,    0,    0,   35,   53,
        0,   53,    0,   53,    0,   53,    0,    2,   15,    0,
        0,    0,    0,    0,    0,   53,    0,    0,   53,    0,
        0,   53,    0,    0,   53,    0,    0,    0,    0,    0,
        0,    0,    0,   53,    0,    0,   53,    0,    0,   53,
        0,    0,   53,    0,    0,    0,    0,    0,    0,    0,
        0,   53,    0,    0,   53,    0,    0,   53,    0,    0,
       53,    0,    0,    0,    0,    0,   31,    0,    0,   53,

        0,    0,   53,    0,    0,   53,    0,    0,   53,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   32,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   29,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   30,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   33,   34,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   38,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   40,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   41,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       46,    0,   39,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   48,
        0,    0,    0,    0,    0,    0,    0,   49,   42,    0,
        0,    0,    0,    0,   47,    0,    0,    0,   44,    0,

        0,   45,    0,   43,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   23,   23,   23,   23,   24,    1,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   45,   50,   45,   45,   51,
        1,   52,    1,   53,   54,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   45,   64,   65,   66,   67,
       68,   69,   45,   70,   71,   72,   73,   74,   75,   76,
       77,   51,    1,   78,    1,    1,    1,    1,    1,    1,
        1,   79,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   79,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   79,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[80] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    3
    } ;

static const flex_int16_t yy_base[510] =
    {   0,
        0,    0,  825,  826,  826,  826,   74,    0,  816,  814,
      826,  826,  826,   63,  826,   71,   73,  826,  796,  797,
       79,   80,   81,   91,   86,  804,   82,   87,   89,   90,
       92,  141,  826,  826,  101,   94,  103,  107,  102,  741,
      119,  826,  121,    0,  749,  826,  156,  801,  162,  172,
      188,  826,  826,  826,  826,  826,  140,  181,   98,  826,
      180,  153,  151,  171,  170,  800,   99,  184,  115,   80,
      185,  201,  202,  204,  198,  799,  826,  205,  826,  218,
      737,  257,  241,  265,  797,  211,  217,  257,  235,  218,
      209,  238,  230,  826,  796,  104,  761,  755,  280,  281,

      282,  283,  241,  229,  737,  300,  292,  792,  279,  291,
      286,  287,  213,  308,  297,  298,  309,  206,  181,  742,
      310,  216,  311,  330,  320,  333,  322,  335,  790,  332,
      743,  334,  319,  788,  336,  337,  757,  339,  355,  340,
      341,  366,  730,  731,  746,  342,  743,  344,  742,  352,
      741,  353,  740,  779,  726,  367,  777,  369,  368,  729,
      372,  737,  363,  371,  771,  717,  724,  345,  373,  732,
      374,  731,  376,  730,  378,  729,  716,  381,  380,  379,
      721,  765,  747,  385,  391,  761,  707,  826,  722,  747,
      345,  710,  387,  709,  390,  708,  406,  707,  422,  386,

      755,  754,  707,  692,  407,  409,  749,  826,  694,  716,
      412,  710,  415,  709,  416,  708,  417,  707,  452,  459,
      460,  419,  688,  690,  462,  463,  746,  700,  826,  422,
       97,  458,  203,  459,  441,  464,  435,  484,  740,  701,
      695,  697,  696,  697,  688,  460,  681,  680,  467,  679,
      678,  468,  686,  676,  471,  684,  674,  711,  673,  684,
      683,  693,  677,  477,  660,  664,  478,  675,  662,  480,
      676,  660,  481,  655,  658,  672,  668,  660,  659,  655,
      651,  483,  667,  656,  486,  660,  654,  487,  643,  652,
      489,  656,  650,  648,  653,  657,  826,  647,  655,  490,

      674,  653,  491,  636,  651,  498,  627,  649,  500,  632,
      647,  645,  641,  657,  630,  669,  639,  639,  653,  636,
      636,  649,  633,  634,  651,  630,  626,  637,  616,  826,
      627,  609,  626,  624,  606,  609,  621,  603,  606,  618,
      638,  612,  615,  615,  609,  610,  594,  594,  644,  598,
      599,  586,  595,  600,  600,  592,  601,  600,  589,  619,
      578,  592,  593,  826,  610,  594,  586,  592,  591,  590,
      584,  588,  569,  566,  585,  583,  578,  826,  574,  597,
      594,  560,  598,  590,  596,  559,  592,  564,  549,  578,
      552,  553,  826,  826,  554,  562,  565,  551,  563,  562,

      557,  554,  560,  554,  549,  552,  535,  826,  537,  550,
      535,  534,  550,  531,  569,  528,  540,  546,  545,  535,
      538,  533,  536,  520,  534,  537,  532,  517,  555,  554,
      526,  516,  524,  530,  506,  826,  510,  511,  521,  524,
      523,  504,  521,  502,  540,  519,  509,  512,  826,  498,
      497,  509,  495,  507,  510,  530,  502,  508,  498,  497,
      826,  500,  826,  486,  502,  483,  521,  493,  492,  498,
      488,  478,  490,  489,  465,  457,  495,  467,  464,  826,
      454,  466,  465,  468,  449,  460,  457,  826,  826,  447,
      459,  444,  452,  446,  826,  439,  336,  347,  826,  208,

      168,  826,   74,  826,  826,  539,  542,  108,  545
    } ;

static const flex_int16_t yy_def[510] =
    {   0,
      505,    1,  505,  505,  505,  505,  506,  507,  505,  505,
      505,  505,  505,  505,  505,  508,  505,  505,  505,  505,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  505,  505,  508,  508,  508,  508,  508,  505,
      506,  505,  506,  507,  505,  505,  505,  508,  505,  508,
      508,  505,  505,  505,  505,  505,  508,  508,  508,  505,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  505,
      508,  508,  508,  508,  508,  508,  505,  508,  505,  506,
      505,  505,  505,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  505,  508,  508,  505,  505,  508,  508,

      508,  508,  508,  508,  505,  505,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  505,  505,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      505,  508,  508,  508,  508,  508,  505,  508,  508,  508,
      508,  508,  505,  505,  505,  508,  505,  508,  505,  508,
      505,  508,  505,  508,  505,  508,  508,  508,  508,  505,
      508,  505,  508,  508,  505,  505,  505,  505,  508,  505,
      508,  505,  508,  505,  508,  505,  505,  508,  508,  508,
      505,  508,  505,  508,  508,  505,  505,  505,  505,  505,
      508,  505,  508,  505,  508,  505,  508,  505,  509,  508,

      508,  508,  505,  505,  508,  508,  505,  505,  505,  505,
      508,  505,  508,  505,  508,  505,  508,  505,  509,  509,
      509,  508,  505,  505,  508,  508,  505,  505,  505,  508,
      505,  508,  505,  508,  505,  508,  505,  509,  508,  505,
      505,  505,  505,  505,  505,  508,  505,  505,  508,  505,
      505,  508,  505,  505,  508,  505,  505,  505,  505,  505,
      505,  505,  505,  508,  505,  505,  508,  505,  505,  508,
      505,  505,  508,  505,  505,  505,  505,  505,  505,  505,
      505,  508,  505,  505,  508,  505,  505,  508,  505,  505,
      508,  505,  505,  505,  505,  505,  505,  505,  505,  508,

      505,  505,  508,  505,  505,  508,  505,  505,  508,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,

      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,

      505,  505,  505,  505,    0,  505,  505,  505,  505
    } ;

static const flex_int16_t yy_nxt[906] =
    {   0,
        4,    5,    6,    5,    5,    7,    8,    9,   10,    4,
        4,    4,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,    4,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   26,   26,   26,   26,   26,   27,
       28,   26,   29,   26,   26,   26,   30,   31,   26,   32,
       26,    4,   33,   34,   21,   22,   23,   24,   35,   26,
       26,   26,   36,   26,   26,   37,   26,   29,   26,   26,
       30,   38,   26,   26,   39,   26,   26,   40,    4,   42,
       47,   47,   47,   47,   47,   47,   49,   52,   50,   50,
       50,   50,   50,   50,  505,  505,  505,  505,   53,   54,

       60,  505,  505,   51,  505,  505,  505,  505,   94,  505,
       48,   77,   58,  505,  505,   63,  505,  505,  505,  505,
       57,   67,  505,   59,   42,   43,   80,   61,   68,   51,
      505,   63,  504,   97,   66,   98,  247,   69,   58,   88,
       62,   64,   61,   68,  118,   57,  248,   67,   59,   65,
       70,   96,   61,   76,   68,  505,  505,   63,   66,   71,
       72,   73,   74,   78,   88,   75,  505,   61,  505,   68,
       43,   85,   43,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,  505,  505,   49,   82,   50,
       50,   50,   50,   50,   50,  505,  505,   85,   91,  505,

      505,   83,   83,  505,   51,   84,   84,   84,   84,   84,
       84,   89,   90,  505,   82,   86,  505,  505,   91,  505,
      505,  505,   91,   42,  505,  147,  505,   87,  505,  137,
       51,  505,  505,  505,   95,  143,   93,   89,   99,  114,
      503,   86,   91,  250,  505,  505,   92,  107,  144,  142,
      505,   87,  251,  505,  100,  101,  505,  102,  106,  106,
      106,  106,  106,  106,  108,  114,  502,  104,  103,   43,
       83,   83,  505,  107,  106,  106,  106,  106,  106,  106,
      505,  112,   84,   84,   84,   84,   84,   84,  108,  113,
      109,  115,  117,  130,  505,  505,  505,  505,  505,  129,

      116,  505,  505,  110,  111,  112,  505,  505,  121,  123,
      125,  127,  505,  505,  135,  133,  109,  106,  106,  106,
      106,  106,  106,  505,  505,  505,  505,  110,  111,  122,
      124,  126,  128,  132,  505,  505,  136,  505,  134,  149,
      135,  133,  151,  138,  153,  505,  139,  505,  505,  505,
      505,  505,  505,  157,  505,  505,  505,  505,  132,  505,
      505,  136,  134,  140,  162,  146,  148,  505,  505,  138,
      505,  161,  158,  159,  141,  150,  165,  152,  505,  157,
      156,  505,  505,  505,  505,  189,  505,  505,  505,  505,
      154,  505,  190,  505,  505,  505,  505,  161,  158,  159,

      505,  505,  505,  211,  156,  505,  505,  501,  500,  169,
      179,  171,  163,  164,  202,  180,  178,  200,  182,  173,
      175,  505,  505,  220,  505,  220,  201,  505,  184,  221,
      505,  505,  505,  222,  505,  179,  185,  505,  205,  180,
      202,  178,  182,  200,  206,  213,  191,  193,  215,  195,
      201,  197,  246,  220,  239,  220,  225,  222,  226,  221,
      220,  220,  220,  220,  217,  230,  221,  238,  232,  234,
      236,  242,  243,  505,  505,  505,  253,  505,  505,  505,
      239,  256,  505,  505,  257,  220,  505,  220,  249,  252,
      254,  238,  505,  505,  255,  505,  505,  499,  505,  317,

      320,  505,  505,  264,  505,  505,  505,  323,  498,  326,
      267,  270,  497,  505,  273,  505,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  484,  483,
      282,  285,  300,  288,  291,  303,  306,  482,  309,   41,
       41,   41,   44,  481,   44,  219,  219,  219,  480,  479,
      478,  477,  476,  475,  474,  473,  472,  471,  470,  469,
      468,  467,  466,  465,  464,  463,  462,  461,  460,  459,
      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,

      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  366,  365,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,

      328,  327,  325,  324,  322,  321,  319,  318,  316,  315,
      314,  313,  312,  311,  310,  308,  307,  305,  304,  302,
      301,  299,  298,  297,  296,  295,  294,  293,  292,  290,
      289,  287,  286,  284,  283,  281,  280,  279,  278,  277,
      276,  275,  274,  272,  271,  269,  268,  266,  265,  263,
      262,  261,  260,  259,  258,  505,  245,  244,  241,  240,
      237,  235,  233,  231,  229,  228,  227,  224,  223,  505,
      505,  218,  216,  214,  212,  210,  209,  208,  207,  204,
      505,  203,  199,  198,  196,  194,  192,  188,  187,  186,
      183,  181,  505,  177,  505,  176,  174,  172,  170,  168,

      167,  166,  160,  505,  155,  505,  145,  505,  131,  120,
      119,  505,  505,  105,  505,  505,  505,   81,   79,  505,
       56,   55,   46,   45,  505,    3,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,

      505,  505,  505,  505,  505
    } ;

static const flex_int16_t yy_chk[906] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    7,
       14,   14,   14,   14,   14,   14,   16,   17,   16,   16,
       16,   16,   16,   16,   21,   22,   23,   27,   17,   17,

       24,   25,   28,   16,   29,   30,   24,   31,   67,   36,
      508,   39,   22,   59,   67,   28,   35,   39,   37,   96,
       21,   30,   38,   23,   41,    7,   43,   25,   31,   16,
       69,   37,  503,   70,   29,   70,  231,   31,   22,   59,
       27,   28,   35,   38,   96,   21,  231,   30,   23,   28,
       32,   69,   25,   36,   31,   57,   32,   37,   29,   32,
       32,   32,   32,   39,   59,   35,   63,   35,   62,   38,
       41,   57,   43,   47,   47,   47,   47,   47,   47,   49,
       49,   49,   49,   49,   49,   65,   64,   50,   47,   50,
       50,   50,   50,   50,   50,   61,   58,   57,   63,   68,

       71,   51,   51,   51,   50,   51,   51,   51,   51,   51,
       51,   61,   62,   75,   47,   58,   72,   73,   64,   74,
       78,  118,   63,   80,   91,  122,   86,   58,  113,  113,
       50,  122,   87,   90,   68,  119,   65,   61,   71,   91,
      501,   58,   64,  233,  104,   93,   64,   86,  119,  118,
       89,   58,  233,   92,   72,   73,  103,   74,   83,   83,
       83,   83,   83,   83,   87,   91,  500,   78,   75,   80,
       82,   82,   88,   86,   82,   82,   82,   82,   82,   82,
       84,   89,   84,   84,   84,   84,   84,   84,   87,   90,
       88,   92,   93,  104,  109,   99,  100,  101,  102,  103,

       92,  111,  112,   88,   88,   89,  110,  107,   99,  100,
      101,  102,  115,  116,  111,  109,   88,  106,  106,  106,
      106,  106,  106,  114,  117,  121,  123,   88,   88,   99,
      100,  101,  102,  107,  133,  125,  112,  127,  110,  124,
      111,  109,  126,  114,  128,  124,  115,  130,  126,  132,
      128,  135,  136,  133,  138,  140,  141,  146,  107,  148,
      191,  112,  110,  116,  139,  121,  123,  150,  152,  114,
      139,  138,  135,  136,  117,  125,  142,  127,  163,  133,
      132,  142,  156,  159,  158,  168,  164,  161,  169,  171,
      130,  173,  168,  175,  180,  179,  178,  138,  135,  136,

      184,  200,  193,  191,  132,  195,  185,  498,  497,  146,
      158,  148,  140,  141,  180,  159,  156,  178,  161,  150,
      152,  197,  205,  199,  206,  199,  179,  211,  163,  199,
      213,  215,  217,  200,  222,  158,  164,  230,  184,  159,
      180,  156,  161,  178,  185,  193,  169,  171,  195,  173,
      179,  175,  230,  219,  222,  219,  205,  200,  206,  219,
      220,  221,  220,  221,  197,  211,  220,  221,  213,  215,
      217,  225,  226,  232,  234,  246,  235,  225,  226,  236,
      222,  237,  249,  252,  237,  238,  255,  238,  232,  234,
      235,  238,  264,  267,  236,  270,  273,  496,  282,  300,

      303,  285,  288,  246,  291,  300,  303,  306,  494,  309,
      249,  252,  493,  306,  255,  309,  492,  491,  490,  487,
      486,  485,  484,  483,  482,  481,  479,  478,  477,  476,
      264,  267,  282,  270,  273,  285,  288,  475,  291,  506,
      506,  506,  507,  474,  507,  509,  509,  509,  473,  472,
      471,  470,  469,  468,  467,  466,  465,  464,  462,  460,
      459,  458,  457,  456,  455,  454,  453,  452,  451,  450,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,

      417,  416,  415,  414,  413,  412,  411,  410,  409,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,

      311,  310,  308,  307,  305,  304,  302,  301,  299,  298,
      296,  295,  294,  293,  292,  290,  289,  287,  286,  284,
      283,  281,  280,  279,  278,  277,  276,  275,  274,  272,
      271,  269,  268,  266,  265,  263,  262,  261,  260,  259,
      258,  257,  256,  254,  253,  251,  250,  248,  247,  245,
      244,  243,  242,  241,  240,  239,  228,  227,  224,  223,
      218,  216,  214,  212,  210,  209,  207,  204,  203,  202,
      201,  198,  196,  194,  192,  190,  189,  187,  186,  183,
      182,  181,  177,  176,  174,  172,  170,  167,  166,  165,
      162,  160,  157,  155,  154,  153,  151,  149,  147,  145,

      144,  143,  137,  134,  131,  129,  120,  108,  105,   98,
       97,   95,   85,   81,   76,   66,   48,   45,   40,   26,
       20,   19,   10,    9,    3,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,

      505,  505,  505,  505,  505
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[63] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"

#line 6 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
/*
 * Copyright (c) 2010 Mark Liversedge (liversedge@gmail.com)
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include "DataFilter.h"

// need to get rid of this and use a string...
#include <stdio.h>

#ifdef YY_FLEX_SUBMINOR_VERSION
# define YY_FLEX_VERSION               \
  (YY_FLEX_MAJOR_VERSION) * 1000000 \
+ (YY_FLEX_MINOR_VERSION) * 1000    \
+ (YY_FLEX_SUBMINOR_VERSION)
#else
# define YY_FLEX_VERSION               \
  (YY_FLEX_MAJOR_VERSION) * 1000000 \
+ (YY_FLEX_MINOR_VERSION) * 1000
#endif

// tokens
#include "DataFilter_yacc.h"/* generated by the scanner */

int DataFiltercolumn = 1;

#define YY_USER_ACTION DataFilterlloc.first_line = DataFilterlloc.last_line = DataFilterlineno; \
    DataFilterlloc.first_column = DataFiltercolumn; DataFilterlloc.last_column = DataFiltercolumn + DataFilterleng - 1; \
    DataFiltercolumn += DataFilterleng;

#line 1147 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/DataFilter_lex.cpp"
#define YY_NO_INPUT 1
#line 1149 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/DataFilter_lex.cpp"

#define INITIAL 0

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 57 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"


#line 1359 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/DataFilter_lex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 506 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 505 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 59 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
; /* ignore single-line comments */
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 60 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = PYTHON; return PYTHON;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = EQ; return EQ;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = NEQ; return NEQ;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = LT; return LT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = LTE; return LTE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = GT; return GT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = GTE; return GTE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = ELVIS; return ELVIS;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = ASSIGN; return ASSIGN;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 70 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = IF_; return IF_;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = ELSE_; return ELSE_;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = WHILE; return WHILE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 75 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = MATCHES; return MATCHES;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 76 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = BEGINSWITH; return BEGINSWITH;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 77 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = ENDSWITH; return ENDSWITH;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 78 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = CONTAINS; return CONTAINS;
	YY_BREAK
/* functions identified by name in the lexer is probably
                                              going to limit us in the future */
case 18:
YY_RULE_SETUP
#line 82 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
strcpy(DataFilterlval.function, "best"); return BEST;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 83 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
strcpy(DataFilterlval.function, "tiz"); return TIZ;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 84 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
strcpy(DataFilterlval.function, "config"); return CONFIG;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
strcpy(DataFilterlval.function, "const"); return CONST_;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 87 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = AND; return AND;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 88 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = AND; return AND;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 89 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = OR; return OR;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 90 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = OR; return OR;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 92 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return DF_INTEGER;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 93 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return DF_FLOAT;
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 94 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return DF_STRING;  /* contains non-quotes or escaped-quotes */
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 95 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 96 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 97 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 98 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 99 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 101 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 102 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 104 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 105 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 106 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 107 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 108 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 109 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 110 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 111 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 112 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 113 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 114 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 115 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 116 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 117 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 118 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* special case */
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 119 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* symbols can start with 0-9 */
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 120 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return SYMBOL; /* one character symbols */
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 121 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = ADD; return ADD;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 122 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = SUBTRACT; return SUBTRACT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 123 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = MULTIPLY; return MULTIPLY;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 124 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = DIVIDE; return DIVIDE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 125 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
DataFilterlval.op = POW; return POW;
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 128 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
; /* we just ignore whitespace */
	YY_BREAK
/* any other character, typically :, { or } */
case 61:
YY_RULE_SETUP
#line 131 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
return DataFiltertext[0];
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"
ECHO;
	YY_BREAK
#line 1738 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/DataFilter_lex.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 506 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 506 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 505);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 132 "/media/andy/TOSHIBA EXT/Backup2/Documents/GoldenCheetah/src/Core/DataFilter.l"


// Older versions of flex (prior to 2.5.9) do not have the destroy function
// Or We're not using GNU flex then we also won't have a destroy function
#if !defined(FLEX_SCANNER) || (YY_FLEX_VERSION < 2005009)
int DataFilterlex_destroy(void) { return 0; }
#endif

void DataFilter_setString(QString p)
{
    BEGIN(0);
    DataFiltercolumn = 0;
    // internally work with UTF-8 encoding
    // this works for FLEX, since the multi-byte characters only appear WITHIN a "String",
    // but not as part of the grammar - this is important since a char in UTF-8 can have up to 4 bytes
    DataFilter_scan_string(p.toUtf8().data());
}

void DataFilter_clearString()
{
    DataFilterlex_destroy();
}


