######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 8 17:19:06 2007
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += static
LIBS += -lm

# Input
HEADERS += srm.h
SOURCES += srm.cpp

