######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 8 17:19:06 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CXXFLAGS += -std=c99
LIBS += -lm

# Input
SOURCES += srm.cpp

