######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 14 17:16:58 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../../lib
LIBS += ../../lib/libgc.a

# Input
SOURCES += ptunpk.cpp
