/*
 * Interface wrapper code.
 *
 * Generated by SIP 6.15.1
 */

#undef slots
#include "sipAPIgoldencheetah.h"
#define slots Q_SLOTS

#line 59 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
#include "Bindings.h"
#line 12 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonDataSeries.cpp"

#line 28 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
#include <qstring.h>
#line 16 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonDataSeries.cpp"


extern "C" {static PyObject *slot_PythonDataSeries___iter__(PyObject *);}
static PyObject *slot_PythonDataSeries___iter__(PyObject *sipSelf)
{
    ::PythonDataSeries *sipCpp = reinterpret_cast< ::PythonDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonDataSeries));

    if (!sipCpp)
        return SIP_NULLPTR;


    {
        {
            PyObject * sipRes = SIP_NULLPTR;

#line 125 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        sipRes = PySeqIter_New(sipSelf);
#line 34 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonDataSeries.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static int slot_PythonDataSeries___setitem__(PyObject *, PyObject *);}
static int slot_PythonDataSeries___setitem__(PyObject *sipSelf, PyObject *sipArgs)
{
    ::PythonDataSeries *sipCpp = reinterpret_cast< ::PythonDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonDataSeries));

    if (!sipCpp)
        return -1;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        long a0;
        double a1;

        if (sipParseArgs(&sipParseErr, sipArgs, "ld", &a0, &a1))
        {
            sipErrorState sipError = sipErrorNone;

#line 104 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        if (sipCpp->readOnly) {
            PyErr_SetString(PyExc_AttributeError, "Object is read-only");
            sipError = sipErrorFail;
        } else {
            if (a0 < 0) a0 += sipCpp->count;
            if (a0 >= 0 && a0 < sipCpp->count) {
                sipCpp->data[a0] = a1;
                RideFile *rideFile = sipCpp->rideFile;
                if (rideFile) {
                    RideFile::SeriesType seriesType = static_cast<RideFile::SeriesType>(sipCpp->seriesType);
                    rideFile->command->setPointValue(a0, seriesType, a1);
                    if (!rideFile->isDataPresent(seriesType)) rideFile->command->setDataPresent(seriesType, true);
                }
            } else {
                PyErr_SetString(PyExc_IndexError, "Index out of range");
                sipError = sipErrorFail;
            }
        }
#line 81 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonDataSeries.cpp"

            if (sipError == sipErrorFail)
                return -1;

            if (sipError == sipErrorNone)
            {
            return 0;
            }

            sipAddException(sipError, &sipParseErr);
        }
    }

    sipNoMethod(sipParseErr, sipName_PythonDataSeries, sipName___setitem__, SIP_NULLPTR);

    return -1;
}


extern "C" {static PyObject *slot_PythonDataSeries___getitem__(PyObject *, PyObject *);}
static PyObject *slot_PythonDataSeries___getitem__(PyObject *sipSelf, PyObject *sipArg)
{
    ::PythonDataSeries *sipCpp = reinterpret_cast< ::PythonDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonDataSeries));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        long a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1l", &a0))
        {
            double sipRes = 0;
            sipErrorState sipError = sipErrorNone;

#line 94 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        if (a0 < 0) a0 += sipCpp->count;
        if (a0 >= 0 && a0 < sipCpp->count) {
            sipRes = sipCpp->data[a0];
        } else {
            PyErr_SetString(PyExc_IndexError, "Index out of range");
            sipError = sipErrorFail;
        }
#line 127 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonDataSeries.cpp"

            if (sipError == sipErrorFail)
                return 0;

            if (sipError == sipErrorNone)
            {
            return PyFloat_FromDouble(sipRes);
            }

            sipAddException(sipError, &sipParseErr);
        }
    }

    sipNoMethod(sipParseErr, sipName_PythonDataSeries, sipName___getitem__, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static Py_ssize_t slot_PythonDataSeries___len__(PyObject *);}
static Py_ssize_t slot_PythonDataSeries___len__(PyObject *sipSelf)
{
    ::PythonDataSeries *sipCpp = reinterpret_cast< ::PythonDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonDataSeries));

    if (!sipCpp)
        return 0;


    {
        {
            Py_ssize_t sipRes = 0;

#line 90 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        sipRes = sipCpp->count;
#line 162 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonDataSeries.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_PythonDataSeries___str__(PyObject *);}
static PyObject *slot_PythonDataSeries___str__(PyObject *sipSelf)
{
    ::PythonDataSeries *sipCpp = reinterpret_cast< ::PythonDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonDataSeries));

    if (!sipCpp)
        return SIP_NULLPTR;


    {
        {
            ::QString*sipRes = 0;

#line 86 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        sipRes = new QString(sipCpp->name);
#line 187 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonDataSeries.cpp"

            return sipConvertFromNewType(sipRes, sipType_QString, SIP_NULLPTR);
        }
    }

    return 0;
}


/* Call the instance's destructor. */
extern "C" {static void release_PythonDataSeries(void *, int);}
static void release_PythonDataSeries(void *sipCppV, int)
{
    delete reinterpret_cast< ::PythonDataSeries *>(sipCppV);
}


extern "C" {static int getbuffer_PythonDataSeries(PyObject *, void *, Py_buffer *, int);}
static int getbuffer_PythonDataSeries(PyObject *sipSelf, void *sipCppV, Py_buffer *sipBuffer, int )
{
    ::PythonDataSeries *sipCpp = reinterpret_cast< ::PythonDataSeries *>(sipCppV);
    int sipRes;

#line 63 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
    sipBuffer->obj = sipSelf;
    sipBuffer->buf = (void*)sipCpp->data;
    sipBuffer->len = sipCpp->count * sizeof(double);
    sipBuffer->readonly = 0;
    sipBuffer->itemsize = sizeof(double);
    sipBuffer->format = (char*)"d";  // double
    sipBuffer->ndim = 1;
    sipBuffer->shape = &sipCpp->count;  // length-1 sequence of dimensions
    sipBuffer->strides = &sipBuffer->itemsize;  // for the simple case we can do this
    sipBuffer->suboffsets = NULL;
    sipBuffer->internal = NULL;

    Py_INCREF(sipSelf);  // need to increase the reference count
    sipRes = 0;
#line 226 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonDataSeries.cpp"

    return sipRes;
}


extern "C" {static void releasebuffer_PythonDataSeries(PyObject *, void *, Py_buffer *);}
static void releasebuffer_PythonDataSeries(PyObject *, void *, Py_buffer *)
{
#line 80 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
    // we do not require any special release function
#line 237 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonDataSeries.cpp"
}


extern "C" {static void *array_PythonDataSeries(Py_ssize_t);}
static void *array_PythonDataSeries(Py_ssize_t sipNrElem)
{
    return new ::PythonDataSeries[sipNrElem];
}


extern "C" {static void array_delete_PythonDataSeries(void *);}
static void array_delete_PythonDataSeries(void *sipCpp)
{
    delete[] reinterpret_cast< ::PythonDataSeries *>(sipCpp);
}


extern "C" {static void assign_PythonDataSeries(void *, Py_ssize_t, void *);}
static void assign_PythonDataSeries(void *sipDst, Py_ssize_t sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::PythonDataSeries *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::PythonDataSeries *>(sipSrc);
}


extern "C" {static void *copy_PythonDataSeries(const void *, Py_ssize_t);}
static void *copy_PythonDataSeries(const void *sipSrc, Py_ssize_t sipSrcIdx)
{
    return new ::PythonDataSeries(reinterpret_cast<const ::PythonDataSeries *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_PythonDataSeries(sipSimpleWrapper *);}
static void dealloc_PythonDataSeries(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_PythonDataSeries(sipGetAddress(sipSelf), 0);
    }
}


extern "C" {static void *init_type_PythonDataSeries(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_PythonDataSeries(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    ::PythonDataSeries *sipCpp = SIP_NULLPTR;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, ""))
        {
            sipCpp = new ::PythonDataSeries();

            return sipCpp;
        }
    }

    {
        const ::PythonDataSeries* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J9", sipType_PythonDataSeries, &a0))
        {
            sipCpp = new ::PythonDataSeries(*a0);

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


/* Define this type's Python slots. */
static sipPySlotDef slots_PythonDataSeries[] = {
    {(void *)slot_PythonDataSeries___iter__, iter_slot},
    {(void *)slot_PythonDataSeries___setitem__, setitem_slot},
    {(void *)slot_PythonDataSeries___getitem__, getitem_slot},
    {(void *)slot_PythonDataSeries___len__, len_slot},
    {(void *)slot_PythonDataSeries___str__, str_slot},
    {0, (sipPySlotType)0}
};

PyDoc_STRVAR(doc_PythonDataSeries, "\1PythonDataSeries()\n"
"PythonDataSeries(a0: PythonDataSeries)");


sipClassTypeDef sipTypeDef_goldencheetah_PythonDataSeries = {
    {
        SIP_NULLPTR,
        SIP_TYPE_CLASS,
        sipNameNr_PythonDataSeries,
        SIP_NULLPTR,
        SIP_NULLPTR,
    },
    {
        sipNameNr_PythonDataSeries,
        {0, 0, 1},
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    doc_PythonDataSeries,
    -1,
    -1,
    SIP_NULLPTR,
    slots_PythonDataSeries,
    init_type_PythonDataSeries,
    SIP_NULLPTR,
    SIP_NULLPTR,
    getbuffer_PythonDataSeries,
    releasebuffer_PythonDataSeries,
    dealloc_PythonDataSeries,
    assign_PythonDataSeries,
    array_PythonDataSeries,
    copy_PythonDataSeries,
    release_PythonDataSeries,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    array_delete_PythonDataSeries,
    sizeof (::PythonDataSeries),
};
