/*
 * Module code.
 *
 * Generated by SIP 6.15.1
 */

#undef slots
#include "sipAPIgoldencheetah.h"
#define slots Q_SLOTS

#line 59 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
#include "Bindings.h"
#line 12 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahcmodule.cpp"
#line 248 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
#include "Bindings.h"
#line 15 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahcmodule.cpp"
#line 342 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
//#include "Bindings.h"
#line 18 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahcmodule.cpp"

/* Define the strings used by this module. */
const char sipStrings_goldencheetah[] = {
    'd', 'e', 'l', 'e', 't', 'e', 'A', 'c', 't', 'i', 'v', 'i', 't', 'y', 'S', 'a', 'm', 'p', 'l', 'e', 0,
    'P', 'y', 't', 'h', 'o', 'n', 'X', 'D', 'a', 't', 'a', 'S', 'e', 'r', 'i', 'e', 's', 0,
    'a', 'c', 't', 'i', 'v', 'i', 't', 'y', 'I', 'n', 't', 'e', 'r', 'v', 'a', 'l', 's', 0,
    'c', 'r', 'e', 'a', 't', 'e', 'X', 'D', 'a', 't', 'a', 'S', 'e', 'r', 'i', 'e', 's', 0,
    'd', 'e', 'l', 'e', 't', 'e', 'X', 'D', 'a', 't', 'a', 'S', 'e', 'r', 'i', 'e', 's', 0,
    'P', 'y', 't', 'h', 'o', 'n', 'D', 'a', 't', 'a', 'S', 'e', 'r', 'i', 'e', 's', 0,
    'a', 'c', 't', 'i', 'v', 'i', 't', 'y', 'M', 'e', 'a', 'n', 'm', 'a', 'x', 0,
    'a', 'c', 't', 'i', 'v', 'i', 't', 'y', 'M', 'e', 't', 'r', 'i', 'c', 's', 0,
    's', 'e', 'a', 's', 'o', 'n', 'I', 'n', 't', 'e', 'r', 'v', 'a', 'l', 's', 0,
    's', 'e', 'a', 's', 'o', 'n', 'M', 'e', 'a', 's', 'u', 'r', 'e', 's', 0,
    'a', 'd', 'd', 'A', 'n', 'n', 'o', 't', 'a', 't', 'i', 'o', 'n', 0,
    'g', 'o', 'l', 'd', 'e', 'n', 'c', 'h', 'e', 'e', 't', 'a', 'h', 0,
    's', 'e', 'a', 's', 'o', 'n', 'M', 'e', 'a', 'n', 'm', 'a', 'x', 0,
    's', 'e', 'a', 's', 'o', 'n', 'M', 'e', 't', 'r', 'i', 'c', 's', 0,
    's', 'e', 'r', 'i', 'e', 's', 'P', 'r', 'e', 's', 'e', 'n', 't', 0,
    'a', 'c', 't', 'i', 'v', 'i', 't', 'y', 'W', 'b', 'a', 'l', 0,
    'a', 't', 'h', 'l', 'e', 't', 'e', 'Z', 'o', 'n', 'e', 's', 0,
    'c', 'o', 'm', 'p', 'a', 'r', 'e', 'i', 'n', 'd', 'e', 'x', 0,
    'd', 'e', 'l', 'e', 't', 'e', 'S', 'e', 'r', 'i', 'e', 's', 0,
    'i', 'n', 't', 'e', 'r', 'v', 'a', 'l', 'T', 'y', 'p', 'e', 0,
    'Q', 'S', 't', 'r', 'i', 'n', 'g', 'L', 'i', 's', 't', 0,
    '_', '_', 'g', 'e', 't', 'i', 't', 'e', 'm', '_', '_', 0,
    '_', '_', 's', 'e', 't', 'i', 't', 'e', 'm', '_', '_', 0,
    'c', 'o', 'n', 'f', 'i', 'g', 'C', 'h', 'a', 'r', 't', 0,
    'd', 'e', 'l', 'e', 't', 'e', 'X', 'D', 'a', 't', 'a', 0,
    'o', 'r', 'i', 'e', 'n', 't', 'a', 't', 'i', 'o', 'n', 0,
    'p', 'o', 's', 't', 'P', 'r', 'o', 'c', 'e', 's', 's', 0,
    's', 'e', 'a', 's', 'o', 'n', 'P', 'e', 'a', 'k', 's', 0,
    'x', 'd', 'a', 't', 'a', 'S', 'e', 'r', 'i', 'e', 's', 0,
    'a', 'c', 't', 'i', 'v', 'i', 't', 'i', 'e', 's', 0,
    'c', 'a', 't', 'e', 'g', 'o', 'r', 'i', 'e', 's', 0,
    'c', 'o', 'n', 'f', 'i', 'g', 'A', 'x', 'i', 's', 0,
    'd', 'a', 't', 'a', 'l', 'a', 'b', 'e', 'l', 's', 0,
    'l', 'a', 'b', 'e', 'l', 'c', 'o', 'l', 'o', 'r', 0,
    's', 'e', 'r', 'i', 'e', 's', 'L', 'a', 's', 't', 0,
    's', 'e', 'r', 'i', 'e', 's', 'N', 'a', 'm', 'e', 0,
    's', 'e', 'r', 'i', 'e', 's', 'U', 'n', 'i', 't', 0,
    's', 'y', 'm', 'b', 'o', 'l', 's', 'i', 'z', 'e', 0,
    'x', 'd', 'a', 't', 'a', 'N', 'a', 'm', 'e', 's', 0,
    'p', 'r', 'o', 'c', 'e', 's', 's', 'o', 'r', 0,
    's', 'e', 'a', 's', 'o', 'n', 'P', 'm', 'c', 0,
    'B', 'i', 'n', 'd', 'i', 'n', 'g', 's', 0,
    '_', '_', 'i', 't', 'e', 'r', '_', '_', 0,
    'a', 'c', 't', 'i', 'v', 'i', 't', 'y', 0,
    'd', 'u', 'r', 'a', 't', 'i', 'o', 'n', 0,
    's', 'e', 't', 'C', 'u', 'r', 'v', 'e', 0,
    't', 'h', 'r', 'e', 'a', 'd', 'i', 'd', 0,
    'Q', 'S', 't', 'r', 'i', 'n', 'g', 0,
    '_', '_', 'l', 'e', 'n', '_', '_', 0,
    '_', '_', 's', 't', 'r', '_', '_', 0,
    'a', 'n', 'i', 'm', 'a', 't', 'e', 0,
    'a', 't', 'h', 'l', 'e', 't', 'e', 0,
    'c', 'o', 'm', 'p', 'a', 'r', 'e', 0,
    'f', 's', 'e', 'r', 'i', 'e', 's', 0,
    'm', 'e', 't', 'r', 'i', 'c', 's', 0,
    'o', 'p', 'a', 'c', 'i', 't', 'y', 0,
    'v', 'e', 'r', 's', 'i', 'o', 'n', 0,
    'v', 'i', 's', 'i', 'b', 'l', 'e', 0,
    'w', 'e', 'b', 'p', 'a', 'g', 'e', 0,
    'x', 's', 'e', 'r', 'i', 'e', 's', 0,
    'y', 's', 'e', 'r', 'i', 'e', 's', 0,
    'a', 'p', 'p', 'e', 'n', 'd', 0,
    'c', 'o', 'l', 'o', 'r', 's', 0,
    'd', 'e', 'l', 'T', 'a', 'g', 0,
    'f', 'i', 'l', 't', 'e', 'r', 0,
    'g', 'e', 't', 'T', 'a', 'g', 0,
    'h', 'a', 's', 'T', 'a', 'g', 0,
    'l', 'e', 'g', 'e', 'n', 'd', 0,
    'l', 'e', 'g', 'p', 'o', 's', 0,
    'm', 'e', 't', 'r', 'i', 'c', 0,
    'o', 'p', 'e', 'n', 'g', 'l', 0,
    'r', 'e', 'm', 'o', 'v', 'e', 0,
    'r', 'e', 's', 'u', 'l', 't', 0,
    's', 'e', 'a', 's', 'o', 'n', 0,
    's', 'e', 't', 'T', 'a', 'g', 0,
    's', 'y', 'm', 'b', 'o', 'l', 0,
    'a', 'l', 'i', 'g', 'n', 0,
    'b', 'u', 'i', 'l', 'd', 0,
    'g', 'r', 'o', 'u', 'p', 0,
    's', 'p', 'o', 'r', 't', 0,
    's', 't', 'a', 'c', 'k', 0,
    't', 'i', 't', 'l', 'e', 0,
    'v', 'a', 'l', 'u', 'e', 0,
    'x', 'd', 'a', 't', 'a', 0,
    'x', 'n', 'a', 'm', 'e', 0,
    'y', 'n', 'a', 'm', 'e', 0,
    'd', 'a', 't', 'e', 0,
    'f', 'i', 'l', 'l', 0,
    'j', 'o', 'i', 'n', 0,
    'l', 'i', 'n', 'e', 0,
    't', 'y', 'p', 'e', 0,
    'a', 'l', 'l', 0,
    'l', 'o', 'g', 0,
    'm', 'i', 'n', 0,
    'u', 'r', 'l', 0,
    's', '1', 0,
    's', '2', 0,
};


/*
 * This defines each type in this module.
 */
sipTypeDef *sipExportedTypes_goldencheetah[] = {
    &sipTypeDef_goldencheetah_Bindings.ctd_base,
    &sipTypeDef_goldencheetah_PythonDataSeries.ctd_base,
    &sipTypeDef_goldencheetah_PythonXDataSeries.ctd_base,
    &sipTypeDef_goldencheetah_QString.mtd_base,
    &sipTypeDef_goldencheetah_QStringList.mtd_base,
};


/* This defines this module. */
sipExportedModuleDef sipModuleAPI_goldencheetah = {
    SIP_NULLPTR,
    11,
    sipNameNr_goldencheetah,
    0,
    sipStrings_goldencheetah,
    SIP_NULLPTR,
    5,
    sipExportedTypes_goldencheetah,
    SIP_NULLPTR,
    0,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
};


/* The SIP API and the APIs of any imported modules. */
const sipAPIDef *sipAPI_goldencheetah;


/* The Python module initialisation function. */
#if defined(SIP_STATIC_MODULE)
extern "C" PyObject *PyInit_goldencheetah()
#else
PyMODINIT_FUNC PyInit_goldencheetah()
#endif
{
    static PyMethodDef sip_methods[] = {
        {SIP_NULLPTR, SIP_NULLPTR, 0, SIP_NULLPTR}
    };
    static PyModuleDef sip_module_def = {
        PyModuleDef_HEAD_INIT,
        "goldencheetah",
        SIP_NULLPTR,
        -1,
        sip_methods,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_NULLPTR
    };

    PyObject *sipModule, *sipModuleDict;
    /* Initialise the module and get it's dictionary. */
    if ((sipModule = PyModule_Create(&sip_module_def)) == SIP_NULLPTR)
        return SIP_NULLPTR;

    sipModuleDict = PyModule_GetDict(sipModule);

    if ((sipAPI_goldencheetah = sip_init_library(sipModuleDict)) == SIP_NULLPTR)
        return SIP_NULLPTR;

    /* Export the module and publish it's API. */
    if (sipExportModule(&sipModuleAPI_goldencheetah, 13, 11, 0) < 0)
    {
        Py_DECREF(sipModule);
        return SIP_NULLPTR;
    }

    /* Initialise the module now all its dependencies have been set up. */
    if (sipInitModule(&sipModuleAPI_goldencheetah, sipModuleDict) < 0)
    {
        Py_DECREF(sipModule);
        return SIP_NULLPTR;
    }

    return sipModule;
}
