/*
 * Interface wrapper code.
 *
 * Generated by SIP 6.15.1
 */

#undef slots
#include "sipAPIgoldencheetah.h"
#define slots Q_SLOTS

#line 248 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
#include "Bindings.h"
#line 12 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"

#line 28 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
#include <qstring.h>
#line 16 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"


PyDoc_STRVAR(doc_PythonXDataSeries_append, "append(self, a0: float)");

extern "C" {static PyObject *meth_PythonXDataSeries_append(PyObject *, PyObject *);}
static PyObject *meth_PythonXDataSeries_append(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
        double a0;
        ::PythonXDataSeries *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bd", &sipSelf, sipType_PythonXDataSeries, &sipCpp, &a0))
        {
            sipErrorState sipError = sipErrorNone;

#line 310 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        if (sipCpp->readOnly) {
            PyErr_SetString(PyExc_AttributeError, "Object is read-only");
            sipError = sipErrorFail;
        } else {
            if (!sipCpp->add(a0)) {
                PyErr_SetString(PyExc_RuntimeError, "XData series does not exist");
            }
        }
#line 43 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"

            if (sipError == sipErrorFail)
                return 0;

            if (sipError == sipErrorNone)
            {
            Py_INCREF(Py_None);
            return Py_None;
            }

            sipAddException(sipError, &sipParseErr);
        }
    }

    sipNoMethod(sipParseErr, sipName_PythonXDataSeries, sipName_append, doc_PythonXDataSeries_append);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_PythonXDataSeries_remove, "remove(self, a0: int)");

extern "C" {static PyObject *meth_PythonXDataSeries_remove(PyObject *, PyObject *);}
static PyObject *meth_PythonXDataSeries_remove(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
        long a0;
        ::PythonXDataSeries *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bl", &sipSelf, sipType_PythonXDataSeries, &sipCpp, &a0))
        {
            sipErrorState sipError = sipErrorNone;

#line 321 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        if (sipCpp->readOnly) {
            PyErr_SetString(PyExc_AttributeError, "Object is read-only");
            sipError = sipErrorFail;
        } else {
            if (!sipCpp->remove(a0)) {
                PyErr_SetString(PyExc_RuntimeError, "XData series does not exist");
            }
        }
#line 88 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"

            if (sipError == sipErrorFail)
                return 0;

            if (sipError == sipErrorNone)
            {
            Py_INCREF(Py_None);
            return Py_None;
            }

            sipAddException(sipError, &sipParseErr);
        }
    }

    sipNoMethod(sipParseErr, sipName_PythonXDataSeries, sipName_remove, doc_PythonXDataSeries_remove);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *slot_PythonXDataSeries___iter__(PyObject *);}
static PyObject *slot_PythonXDataSeries___iter__(PyObject *sipSelf)
{
    ::PythonXDataSeries *sipCpp = reinterpret_cast< ::PythonXDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonXDataSeries));

    if (!sipCpp)
        return SIP_NULLPTR;


    {
        {
            PyObject * sipRes = SIP_NULLPTR;

#line 332 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        sipRes = PySeqIter_New(sipSelf);
#line 124 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static int slot_PythonXDataSeries___setitem__(PyObject *, PyObject *);}
static int slot_PythonXDataSeries___setitem__(PyObject *sipSelf, PyObject *sipArgs)
{
    ::PythonXDataSeries *sipCpp = reinterpret_cast< ::PythonXDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonXDataSeries));

    if (!sipCpp)
        return -1;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        long a0;
        double a1;

        if (sipParseArgs(&sipParseErr, sipArgs, "ld", &a0, &a1))
        {
            sipErrorState sipError = sipErrorNone;

#line 293 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        if (sipCpp->readOnly) {
            PyErr_SetString(PyExc_AttributeError, "Object is read-only");
            sipError = sipErrorFail;
        } else {
            if (a0 < 0) a0 += sipCpp->count();
            if (a0 >= 0 && a0 < sipCpp->count()) {
                if (!sipCpp->set(a0, a1)) {
                    PyErr_SetString(PyExc_RuntimeError, "XData series does not exist");
                }
            } else {
                PyErr_SetString(PyExc_IndexError, "Index out of range");
                sipError = sipErrorFail;
            }
        }
#line 167 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"

            if (sipError == sipErrorFail)
                return -1;

            if (sipError == sipErrorNone)
            {
            return 0;
            }

            sipAddException(sipError, &sipParseErr);
        }
    }

    sipNoMethod(sipParseErr, sipName_PythonXDataSeries, sipName___setitem__, SIP_NULLPTR);

    return -1;
}


extern "C" {static PyObject *slot_PythonXDataSeries___getitem__(PyObject *, PyObject *);}
static PyObject *slot_PythonXDataSeries___getitem__(PyObject *sipSelf, PyObject *sipArg)
{
    ::PythonXDataSeries *sipCpp = reinterpret_cast< ::PythonXDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonXDataSeries));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        long a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1l", &a0))
        {
            double sipRes = 0;
            sipErrorState sipError = sipErrorNone;

#line 283 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        if (a0 < 0) a0 += sipCpp->count();
        if (a0 >= 0 && a0 < sipCpp->count()) {
            sipRes = sipCpp->get(a0);
        } else {
            PyErr_SetString(PyExc_IndexError, "Index out of range");
            sipError = sipErrorFail;
        }
#line 213 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"

            if (sipError == sipErrorFail)
                return 0;

            if (sipError == sipErrorNone)
            {
            return PyFloat_FromDouble(sipRes);
            }

            sipAddException(sipError, &sipParseErr);
        }
    }

    sipNoMethod(sipParseErr, sipName_PythonXDataSeries, sipName___getitem__, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static Py_ssize_t slot_PythonXDataSeries___len__(PyObject *);}
static Py_ssize_t slot_PythonXDataSeries___len__(PyObject *sipSelf)
{
    ::PythonXDataSeries *sipCpp = reinterpret_cast< ::PythonXDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonXDataSeries));

    if (!sipCpp)
        return 0;


    {
        {
            Py_ssize_t sipRes = 0;

#line 279 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        sipRes = sipCpp->count();
#line 248 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_PythonXDataSeries___str__(PyObject *);}
static PyObject *slot_PythonXDataSeries___str__(PyObject *sipSelf)
{
    ::PythonXDataSeries *sipCpp = reinterpret_cast< ::PythonXDataSeries *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf, sipType_PythonXDataSeries));

    if (!sipCpp)
        return SIP_NULLPTR;


    {
        {
            ::QString*sipRes = 0;

#line 275 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
        sipRes = new QString(sipCpp->name());
#line 273 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"

            return sipConvertFromNewType(sipRes, sipType_QString, SIP_NULLPTR);
        }
    }

    return 0;
}


/* Call the instance's destructor. */
extern "C" {static void release_PythonXDataSeries(void *, int);}
static void release_PythonXDataSeries(void *sipCppV, int)
{
    delete reinterpret_cast< ::PythonXDataSeries *>(sipCppV);
}


extern "C" {static int getbuffer_PythonXDataSeries(PyObject *, void *, Py_buffer *, int);}
static int getbuffer_PythonXDataSeries(PyObject *sipSelf, void *sipCppV, Py_buffer *sipBuffer, int )
{
    ::PythonXDataSeries *sipCpp = reinterpret_cast< ::PythonXDataSeries *>(sipCppV);
    int sipRes;

#line 252 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
    sipBuffer->obj = sipSelf;
    sipBuffer->buf = sipCpp->rawDataPtr();
    sipBuffer->len = sipCpp->count() * sizeof(double);
    sipBuffer->readonly = 0;
    sipBuffer->itemsize = sizeof(double);
    sipBuffer->format = (char*)"d";  // double
    sipBuffer->ndim = 1;
    sipBuffer->shape = sipCpp->shape.data();  // length-1 sequence of dimensions
    sipBuffer->strides = &sipBuffer->itemsize;  // for the simple case we can do this
    sipBuffer->suboffsets = NULL;
    sipBuffer->internal = NULL;

    Py_INCREF(sipSelf);  // need to increase the reference count
    sipRes = 0;
#line 312 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"

    return sipRes;
}


extern "C" {static void releasebuffer_PythonXDataSeries(PyObject *, void *, Py_buffer *);}
static void releasebuffer_PythonXDataSeries(PyObject *, void *, Py_buffer *)
{
#line 269 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
    // we do not require any special release function
#line 323 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahPythonXDataSeries.cpp"
}


extern "C" {static void *array_PythonXDataSeries(Py_ssize_t);}
static void *array_PythonXDataSeries(Py_ssize_t sipNrElem)
{
    return new ::PythonXDataSeries[sipNrElem];
}


extern "C" {static void array_delete_PythonXDataSeries(void *);}
static void array_delete_PythonXDataSeries(void *sipCpp)
{
    delete[] reinterpret_cast< ::PythonXDataSeries *>(sipCpp);
}


extern "C" {static void assign_PythonXDataSeries(void *, Py_ssize_t, void *);}
static void assign_PythonXDataSeries(void *sipDst, Py_ssize_t sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::PythonXDataSeries *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::PythonXDataSeries *>(sipSrc);
}


extern "C" {static void *copy_PythonXDataSeries(const void *, Py_ssize_t);}
static void *copy_PythonXDataSeries(const void *sipSrc, Py_ssize_t sipSrcIdx)
{
    return new ::PythonXDataSeries(reinterpret_cast<const ::PythonXDataSeries *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_PythonXDataSeries(sipSimpleWrapper *);}
static void dealloc_PythonXDataSeries(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_PythonXDataSeries(sipGetAddress(sipSelf), 0);
    }
}


extern "C" {static void *init_type_PythonXDataSeries(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_PythonXDataSeries(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    ::PythonXDataSeries *sipCpp = SIP_NULLPTR;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, ""))
        {
            sipCpp = new ::PythonXDataSeries();

            return sipCpp;
        }
    }

    {
        const ::PythonXDataSeries* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J9", sipType_PythonXDataSeries, &a0))
        {
            sipCpp = new ::PythonXDataSeries(*a0);

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


/* Define this type's Python slots. */
static sipPySlotDef slots_PythonXDataSeries[] = {
    {(void *)slot_PythonXDataSeries___iter__, iter_slot},
    {(void *)slot_PythonXDataSeries___setitem__, setitem_slot},
    {(void *)slot_PythonXDataSeries___getitem__, getitem_slot},
    {(void *)slot_PythonXDataSeries___len__, len_slot},
    {(void *)slot_PythonXDataSeries___str__, str_slot},
    {0, (sipPySlotType)0}
};


static PyMethodDef methods_PythonXDataSeries[] = {
    {sipName_append, meth_PythonXDataSeries_append, METH_VARARGS, doc_PythonXDataSeries_append},
    {sipName_remove, meth_PythonXDataSeries_remove, METH_VARARGS, doc_PythonXDataSeries_remove}
};

PyDoc_STRVAR(doc_PythonXDataSeries, "\1PythonXDataSeries()\n"
"PythonXDataSeries(a0: PythonXDataSeries)");


sipClassTypeDef sipTypeDef_goldencheetah_PythonXDataSeries = {
    {
        SIP_NULLPTR,
        SIP_TYPE_CLASS,
        sipNameNr_PythonXDataSeries,
        SIP_NULLPTR,
        SIP_NULLPTR,
    },
    {
        sipNameNr_PythonXDataSeries,
        {0, 0, 1},
        2, methods_PythonXDataSeries,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    doc_PythonXDataSeries,
    -1,
    -1,
    SIP_NULLPTR,
    slots_PythonXDataSeries,
    init_type_PythonXDataSeries,
    SIP_NULLPTR,
    SIP_NULLPTR,
    getbuffer_PythonXDataSeries,
    releasebuffer_PythonXDataSeries,
    dealloc_PythonXDataSeries,
    assign_PythonXDataSeries,
    array_PythonXDataSeries,
    copy_PythonXDataSeries,
    release_PythonXDataSeries,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    array_delete_PythonXDataSeries,
    sizeof (::PythonXDataSeries),
};
