/*
 * Interface wrapper code.
 *
 * Generated by SIP 6.15.1
 */

#undef slots
#include "sipAPIgoldencheetah.h"
#define slots Q_SLOTS

#line 28 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
#include <qstring.h>
#line 12 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahQString.cpp"



extern "C" {static void assign_QString(void *, Py_ssize_t, void *);}
static void assign_QString(void *sipDst, Py_ssize_t sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::QString *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::QString *>(sipSrc);
}


extern "C" {static void *array_QString(Py_ssize_t);}
static void *array_QString(Py_ssize_t sipNrElem)
{
    return new ::QString[sipNrElem];
}


extern "C" {static void *copy_QString(const void *, Py_ssize_t);}
static void *copy_QString(const void *sipSrc, Py_ssize_t sipSrcIdx)
{
    return new ::QString(reinterpret_cast<const ::QString *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_QString(void *, int, void *);}
static void release_QString(void *sipCppV, int, void *)
{
    ::QString *sipCpp = reinterpret_cast< ::QString *>(sipCppV);
    delete sipCpp;
}



extern "C" {static int convertTo_QString(PyObject *, void **, int *, PyObject *, void **);}
static int convertTo_QString(PyObject *sipPy, void **sipCppPtrV, int *sipIsErr, PyObject *, void **)
{
    ::QString **sipCppPtr = reinterpret_cast< ::QString **>(sipCppPtrV);

#line 32 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
    if (sipIsErr == NULL) return PyUnicode_Check(sipPy);
    if (sipPy == Py_None) {
        *sipCppPtr = new QString();
        return 1;
    }
    if (PyUnicode_Check(sipPy)) {
        Py_ssize_t size;
        wchar_t *string = PyUnicode_AsWideCharString(sipPy, &size);
        if (string) {
            if (size) *sipCppPtr = new QString(QString::fromWCharArray(string));
            else *sipCppPtr = new QString();
        }
        return 1;
    }
    return 0;
#line 68 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahQString.cpp"
}


extern "C" {static PyObject *convertFrom_QString(void *, PyObject *);}
static PyObject *convertFrom_QString(void *sipCppV, PyObject *)
{
    ::QString *sipCpp = reinterpret_cast< ::QString *>(sipCppV);

#line 49 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/goldencheetah.sip"
    return PyUnicode_FromString(sipCpp->toUtf8().data());
#line 79 "/Users/magnusgille/Documents/kod/gc/src/Python/SIP/build/goldencheetah/sipgoldencheetahQString.cpp"
}


sipMappedTypeDef sipTypeDef_goldencheetah_QString = {
    {
        SIP_NULLPTR,
        SIP_TYPE_ALLOW_NONE|SIP_TYPE_MAPPED,
        sipNameNr_QString,
        SIP_NULLPTR,
        SIP_NULLPTR,
    },
    {
        -1,
        {0, 0, 1},
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR}
    },
    assign_QString,
    array_QString,
    copy_QString,
    release_QString,
    convertTo_QString,
    convertFrom_QString
};
