\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename GC3-Manual.texinfo
@settitle Golden Cheetah User Manual
@c %**end of header

@copying
This manual is for Golden Cheetah, version 3.0.

Copyright @copyright{} 2013 Mark Liversedge
@end copying

@titlepage
@title Golden Cheetah User Manual
@c @subtitle subtitle-if-any
@c @subtitle second-subtitle
@author Mark Liversedge

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

@end titlepage

@c So the toc is printed at the start.
@contents

@c ********************************************************************************
@c Welcome chapter
@c ********************************************************************************
@chapter WELCOME TO GOLDENCHEETAH
@node WELCOME

open up with wha is gc and power analysis, cycling, hr training, training journal etc

@section About this latest version, V3.0
whats new -- basic summary of release notes (headings only?)

@section Mailing list and community
google groups

@section Reporting bugs and requesting new features
github

@section Bit of Past, Present and Future
sean, mark, v3, v3.1 plans
 

@c ********************************************************************************
@c Quick start guide
@c ********************************************************************************
@chapter QUICK START GUIDE
@node QUICK

open up with running for the first time, adding an athlete, bank state screens etc

@section basic configuration 
seasons, CP, LTHR

@section importing a ride from device
download dialog

@section importing data from file or other applications
drag and drop

@section uploading and sending your data
upload to TP.com, export file


@c ********************************************************************************
@c Basic Navigation
@c ********************************************************************************
@chapter GETTING AROUND GOLDENCHEETAH
@node NAVIGATION

open up with screen shot and a description of all the basic ui elements, one per athlete etc

@section The Toolbar
what the buttons do

@section Views & Sidebar
scopebar, sidebar, tab/tiled, add chart menu

@section Searching and Filtering
free text search and basics of data filtering

@section Adding and adjusting charts
the dialog, title, settings, finding them again

@section Going fullscreen
key sequences, hiding and showing the toolbar
screensaver?

@section The Metric database
why, what, where, refreshing, exporting 


@c ********************************************************************************
@c Working with Data
@c ********************************************************************************

@chapter IMPORTING EXPORTING DOWNLOADING AND CREATING DATA
@node DATA

@section Download from device
download dialog, basics for each device (plugging in etc)

@section Import from file
selecting a file, the import wizard

@section Manual activity
the manual activity dialog and refer to details screen for more "indepth" (need a better word) stuff

@section Exporting data
   i A single ride
  ii Multiple rides

@section Uploading and Downloading from the Cloud
   i TrainingPeaks
  ii Strava
 iii TrainingStage Buch
  iv RideWithGPS


@c ********************************************************************************
@c ANALYSIS
@c ********************************************************************************

@chapter THE ANALYSIS VIEW
@node ANALYSIS
 
@section About Activities and Intervals
 
@section Sidebar actions and context menus
      o activities
      o intervals

@section Editing and adjusting data
     o using the editor
       i basics
      ii anomalies
     iii find
     o advanced editor functions
       i the 'fix' tools
      ii copying, cutting and pasting

@c ********************************************************************************
@c ANALYSIS CHARTS
@c ********************************************************************************
@chapter Analysis View Charts
@node ANALYSIS CHARTS
       i Activity Summary
      ii Details
     iii Summary and Details
      iv Editor
       v Performance
      vi Critical Mean Maximals
     vii Histogram
    viii Pedal Force vs Velocity
      ix Heartrate vs Power
       x Google Map
      xi Bing Map
     xii 2d Plot
    xiii 3d Plot
     xiv Aerolab Chung Analysis

@c ********************************************************************************
@c HOME
@c ********************************************************************************
@chapter THE HOME VIEW
@node HOME

@section About Date Ranges, Seasons and Events

@c ********************************************************************************
@c HOME CHARTS
@c ********************************************************************************
@chapter Performance Tracking Charts
@node HOME CHARTS
       i Long Term Metrics
         - indepth howto incl. setting up a PMC++
      ii Performance Manager
     iii Collection TreeMap
      iv Critical Mean Maximal
       v Distribution

@c ********************************************************************************
@c DIARY
@c ********************************************************************************
@chapter THE DIARY VIEW
@node DIARY

@section Purpose

@section Summarising for Day / Week / Month

@section Longer term purpose (planning)
 
@c ********************************************************************************
@c TRAIN
@c ********************************************************************************
@chapter THE TRAIN VIEW
@node TRAIN

@section About Devices, Workouts and Video

@section Sidebar actions and context menus
      o devices
      o workouts
      o media

@section Working with the Workout Library
   - Creating a new Workout
   - Getting Workouts from ErgDB
   
@section Setting up and starting a workout
    - Using CT handlebar controller
    - controlling workout from mouse + keyboard

@c ********************************************************************************
@c TRAIN CHARTS
@c ********************************************************************************
@chapter Training View Charts
@node TRAIN CHARTS
        i Telemetry
       ii Workout
      iii Realtime
       iv Pedal Stroke
        v Map
       vi StreetView
      vii Video Player


@c ********************************************************************************
@c Configuration
@c ********************************************************************************
@chapter CONFIGURING
@node CONFIG

Intro and explain opening the Preferences Pane

@section General

@section Athlete
     i About
    ii Power Zones
   iii HR Zones

@section Passwords
    i General
   ii Withings
  iii Zeo
   iv Google Calendar (calDAV)

@section Appearance

@section Data Fields
   i Fields
  ii Notes Keywords
 iii Processing

@section Metrics
   
@section Train Devices
   i Using Multiple Devices
  ii Adding a device
 
@c ********************************************************************************
@c Appendices
@c ********************************************************************************
@chapter APPENDICES
@node APPENDICES

@section A Supported Devices, File Formats and Services
@section B Metrics Reference
@section B Data Filtering Reference
@section C Glossary and Useful Resources (incl. link to FAQ)
@section D OS Specifics (Directories, Drivers and Permissions)

@bye
