######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 14 16:57:18 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../../lib
LIBS += ../../lib/libgc.a

# Input
SOURCES += ptpk.cpp
