
# Copyright (c) 2018 Fredik Lingvall (fredrik.lingvall@protonmail.com)

# LIBSAMPLERATE_INCLUDE_DIR = samplerate.h
# LIBSAMPLERATE_LIBRARIES = libsamplerate.so
# LIBSAMPLERATE_FOUND = true if LIBSAMPLERATE is found

if (WIN32)
  set(CMAKE_PREFIX_PATH "C:/LIBSAMPLERATE")
endif(WIN32)

find_path (LIBSAMPLERATE_INCLUDE_DIR samplerate.h)
if (NOT LIBSAMPLERATE_INCLUDE_DIR)
  message (STATUS "Could not find libsamplerate.h")
endif (NOT LIBSAMPLERATE_INCLUDE_DIR)

find_library (LIBSAMPLERATE_LIBRARIES NAMES libsamplerate samplerate PATH_SUFFIXES lib)
if (NOT LIBSAMPLERATE_LIBRARIES)
  message (STATUS "Could not find LIBSAMPLERATE library")
endif (NOT LIBSAMPLERATE_LIBRARIES)

if (LIBSAMPLERATE_INCLUDE_DIR AND LIBSAMPLERATE_LIBRARIES)
  set (LIBSAMPLERATE_FOUND TRUE)
endif (LIBSAMPLERATE_INCLUDE_DIR AND LIBSAMPLERATE_LIBRARIES)

if (LIBSAMPLERATE_FOUND)

  if (NOT LIBSAMPLERATE_FIND_QUIETLY)
    message (STATUS "Found libsamplerate.h: ${LIBSAMPLERATE_INCLUDE_DIR}")
  endif (NOT LIBSAMPLERATE_FIND_QUIETLY)

  if (NOT LIBSAMPLERATE_FIND_QUIETLY)
    message (STATUS "Found LIBSAMPLERATE: ${LIBSAMPLERATE_LIBRARIES}")
  endif (NOT LIBSAMPLERATE_FIND_QUIETLY)

else (LIBSAMPLERATE_FOUND)
  if (LIBSAMPLERATE_FIND_REQUIRED)
    message (FATAL_ERROR "Could not find LIBSAMPLERATE")
  endif (LIBSAMPLERATE_FIND_REQUIRED)
endif (LIBSAMPLERATE_FOUND)

mark_as_advanced (LIBSAMPLERATE_INCLUDE_DIR LIBSAMPLERATE_LIBRARIES LIBSAMPLERATE_FOUND)
