######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 14 16:54:53 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../../gui
LIBS +=../../gui/cpint.o \
	../../gui/RideFile.o \
	../../gui/CsvRideFile.o \
	../../gui/SrmRideFile.o \
	../../gui/RawRideFile.o \
        ../../srm/libsrm.a \
        ../../lib/libgc.a

# Input
SOURCES += cpint.cpp
