---
name: build

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./.github/scripts/build.sh
      - name: Upload dmg
        uses: actions/upload-artifact@v4
        with:
          name: GoldenCheetah
          path: GoldenCheetah_v3.8_arm64.dmg
