######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 8 17:19:06 2007
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += . ../gui
INCLUDEPATH += . ../lib ../srm ../gui

CONFIG += static debug
LIBS += -lm

# Input
HEADERS += cpint.h
SOURCES += cpint.cpp

