from __future__ import annotations

import json
import os
import sys
import tempfile
import threading
import unittest
from datetime import timedelta
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import anyio
from mcp.client.session import ClientSession
from mcp.client.stdio import StdioServerParameters, stdio_client


ROOT = Path(__file__).resolve().parents[1]


class MockGoldenCheetahHandler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:  # noqa: N802
        if self.path == "/":
            body = "name,dob,weight,height,sex\nTest Rider, 1990/01/01, 72, 180, Male\n"
            self._write(200, body, "text/csv; charset=UTF-8")
            return

        if self.path.startswith("/Test%20Rider/ai/snapshot"):
            body = {
                "snapshot": {
                    "athleteName": "Test Rider",
                    "date": "2026-04-04",
                    "ftp": 250,
                    "cp": 250,
                    "ctl": 65.2,
                    "atl": 70.1,
                    "tsb": -4.9,
                    "canGenerate": True,
                },
                "generatorId": "goldencheetah-heuristic-v1",
                "supportedWorkoutTypes": [
                    "recovery",
                    "endurance",
                    "sweetspot",
                    "threshold",
                    "vo2max",
                    "anaerobic",
                    "mixed",
                ],
            }
            self._write_json(200, body)
            return

        if self.path == "/Test%20Rider":
            body = (
                "date, time, filename\n"
                "2026/04/01, 06:00:00, 2026_04_01_06_00_00.json\n"
                "2026/04/02, 07:00:00, 2026_04_02_07_00_00.json\n"
            )
            self._write(200, body, "text/csv; charset=UTF-8")
            return

        if self.path.startswith("/Test%20Rider/activity/"):
            body = {
                "RIDE": {
                    "STARTTIME": "2026/04/01 06:00:00 UTC",
                    "DEVICETYPE": "Mock Trainer",
                    "SAMPLES": [
                        {"SECS": 0, "WATTS": 150, "HR": 120, "CAD": 85},
                        {"SECS": 1, "WATTS": 155, "HR": 121, "CAD": 86},
                    ],
                }
            }
            self._write_json(200, body)
            return

        if self.path.startswith("/Test%20Rider/meanmax/"):
            body = "seconds, watts\n1, 800\n5, 600\n60, 350\n300, 280\n1200, 250\n"
            self._write(200, body, "text/csv; charset=UTF-8")
            return

        if self.path.startswith("/Test%20Rider/zones"):
            body = "date, cp, wprime, pmax, aetp, ftp\n2026/01/01, 250, 20000, 1000, 200, 250\n"
            self._write(200, body, "text/csv; charset=UTF-8")
            return

        if self.path.startswith("/Test%20Rider/measures"):
            body = "date, weight_kg, body_fat_percent\n2026/04/01, 72, 15.0\n"
            self._write(200, body, "text/csv; charset=UTF-8")
            return

        self._write_json(404, {"error": f"Unhandled GET {self.path}"})

    def do_POST(self) -> None:  # noqa: N802
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length)
        payload = json.loads(raw.decode("utf-8"))

        if self.path == "/Test%20Rider/ai/draft":
            body = {
                "snapshot": {
                    "athleteName": "Test Rider",
                    "date": payload.get("date", "2026-04-04") or "2026-04-04",
                    "ftp": 250,
                    "cp": 250,
                    "ctl": 65.2,
                    "atl": 70.1,
                    "tsb": -4.9,
                    "canGenerate": True,
                },
                "draft": {
                    "schemaVersion": "1",
                    "displayName": payload.get("displayName", "AI Threshold 60min") or "AI Threshold 60min",
                    "description": payload.get("description", "Generated by test harness"),
                    "generatorId": payload.get("generatorId", "goldencheetah-mcp"),
                    "modelId": payload.get("modelId", ""),
                    "modelVersion": payload.get("modelVersion", ""),
                    "steps": [
                        {
                            "durationSec": 600,
                            "powerMode": "percentFtp",
                            "powerValue": 60.0,
                            "label": "Warmup",
                        },
                        {
                            "durationSec": 300,
                            "powerMode": "percentFtp",
                            "powerValue": 100.0,
                            "label": "Threshold 1",
                        },
                    ],
                },
                "warnings": [],
            }
            self._write_json(200, body)
            return

        if self.path == "/Test%20Rider/ai/save":
            draft = payload["draft"]
            body = {
                "saved": True,
                "filepath": "/tmp/mock-workout.erg",
                "displayName": draft.get("displayName", ""),
                "generatorId": draft.get("generatorId", ""),
            }
            self._write_json(200, body)
            return

        if self.path == "/Test%20Rider/ai/plan":
            body = {
                "saved": True,
                "filepath": "/tmp/2026_04_04_06_00_00.json",
                "workoutPath": payload["workoutPath"],
                "when": "2026-04-04T06:00:00",
            }
            self._write_json(200, body)
            return

        self._write_json(404, {"error": f"Unhandled POST {self.path}"})

    def do_DELETE(self) -> None:  # noqa: N802
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length)
        payload = json.loads(raw.decode("utf-8"))

        if self.path == "/Test%20Rider/ai/plan":
            filepath = payload.get("filepath", "")
            body = {"deleted": True, "filepath": filepath}
            self._write_json(200, body)
            return

        self._write_json(404, {"error": f"Unhandled DELETE {self.path}"})

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A003
        return

    def _write_json(self, status: int, payload: dict[str, Any]) -> None:
        self._write(status, json.dumps(payload), "application/json; charset=UTF-8")

    def _write(self, status: int, body: str, content_type: str) -> None:
        data = body.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)


class GoldenCheetahMcpIntegrationTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.httpd = ThreadingHTTPServer(("127.0.0.1", 0), MockGoldenCheetahHandler)
        cls.base_url = f"http://127.0.0.1:{cls.httpd.server_address[1]}"
        cls.thread = threading.Thread(target=cls.httpd.serve_forever, daemon=True)
        cls.thread.start()

    @classmethod
    def tearDownClass(cls) -> None:
        cls.httpd.shutdown()
        cls.thread.join(timeout=5)
        cls.httpd.server_close()

    def test_stdio_tools_round_trip(self) -> None:
        anyio.run(self._exercise_stdio_server)

    async def _exercise_stdio_server(self) -> None:
        env = os.environ.copy()
        env["GC_API_BASE_URL"] = self.base_url

        server = StdioServerParameters(
            command=os.environ.get("PYTHON", str(Path(sys.executable))),
            args=["-m", "goldencheetah_mcp.server", "--transport", "stdio"],
            env=env,
            cwd=ROOT,
        )

        async with stdio_client(server) as (read_stream, write_stream):
            session = ClientSession(
                read_stream,
                write_stream,
                read_timeout_seconds=timedelta(seconds=10),
            )
            async with session:
                await session.initialize()

                tools = await session.list_tools()
                tool_names = {tool.name for tool in tools.tools}
                self.assertIn("gc_list_athletes", tool_names)
                self.assertIn("gc_get_athlete_snapshot", tool_names)
                self.assertIn("gc_create_workout_draft", tool_names)
                self.assertIn("gc_save_workout", tool_names)
                self.assertIn("gc_create_planned_activity", tool_names)

                athletes_result = await session.call_tool("gc_list_athletes")
                athletes = athletes_result.structuredContent["athletes"]
                self.assertEqual(athletes[0]["name"], "Test Rider")

                draft_result = await session.call_tool(
                    "gc_create_workout_draft",
                    {
                        "athlete": "Test Rider",
                        "workout_type": "threshold",
                        "duration_min": 60,
                        "display_name": "Threshold Builder",
                    },
                )
                draft = draft_result.structuredContent["draft"]
                self.assertEqual(draft["displayName"], "Threshold Builder")

                save_result = await session.call_tool(
                    "gc_save_workout",
                    {
                        "athlete": "Test Rider",
                        "draft": draft,
                        "confirm": True,
                    },
                )
                self.assertTrue(save_result.structuredContent["saved"])
                self.assertEqual(save_result.structuredContent["filepath"], "/tmp/mock-workout.erg")

                plan_result = await session.call_tool(
                    "gc_create_planned_activity",
                    {
                        "athlete": "Test Rider",
                        "workout_path": "/tmp/mock-workout.erg",
                        "date": "2026-04-04",
                        "confirm": True,
                    },
                )
                self.assertTrue(plan_result.structuredContent["saved"])
                self.assertEqual(plan_result.structuredContent["filepath"], "/tmp/2026_04_04_06_00_00.json")

    def test_read_tools(self) -> None:
        anyio.run(self._exercise_read_tools)

    async def _exercise_read_tools(self) -> None:
        env = os.environ.copy()
        env["GC_API_BASE_URL"] = self.base_url

        server = StdioServerParameters(
            command=os.environ.get("PYTHON", str(Path(sys.executable))),
            args=["-m", "goldencheetah_mcp.server", "--transport", "stdio"],
            env=env,
            cwd=ROOT,
        )

        async with stdio_client(server) as (read_stream, write_stream):
            session = ClientSession(
                read_stream,
                write_stream,
                read_timeout_seconds=timedelta(seconds=10),
            )
            async with session:
                await session.initialize()

                tools = await session.list_tools()
                tool_names = {tool.name for tool in tools.tools}
                self.assertIn("gc_list_activities", tool_names)
                self.assertIn("gc_get_activity", tool_names)
                self.assertIn("gc_get_meanmax", tool_names)
                self.assertIn("gc_get_zones", tool_names)
                self.assertIn("gc_get_measures", tool_names)
                self.assertIn("gc_list_planned_activities", tool_names)
                self.assertIn("gc_delete_planned_activity", tool_names)
                self.assertIn("gc_update_planned_activity", tool_names)
                self.assertIn("gc_delete_workout", tool_names)

                activities = await session.call_tool(
                    "gc_list_activities",
                    {"athlete": "Test Rider"},
                )
                self.assertIn("csv", activities.structuredContent)
                self.assertIn("2026/04/01", activities.structuredContent["csv"])

                activity = await session.call_tool(
                    "gc_get_activity",
                    {"athlete": "Test Rider", "filename": "2026_04_01_06_00_00.json"},
                )
                self.assertIn("RIDE", activity.structuredContent)

                mmp = await session.call_tool(
                    "gc_get_meanmax",
                    {"athlete": "Test Rider"},
                )
                self.assertIn("csv", mmp.structuredContent)
                self.assertIn("800", mmp.structuredContent["csv"])

                zones = await session.call_tool(
                    "gc_get_zones",
                    {"athlete": "Test Rider"},
                )
                self.assertIn("csv", zones.structuredContent)
                self.assertIn("250", zones.structuredContent["csv"])

                measures = await session.call_tool(
                    "gc_get_measures",
                    {"athlete": "Test Rider", "group": "Body"},
                )
                self.assertIn("csv", measures.structuredContent)
                self.assertIn("72", measures.structuredContent["csv"])

    def test_file_management_tools(self) -> None:
        anyio.run(self._exercise_file_management_tools)

    async def _exercise_file_management_tools(self) -> None:
        env = os.environ.copy()
        env["GC_API_BASE_URL"] = self.base_url

        server = StdioServerParameters(
            command=os.environ.get("PYTHON", str(Path(sys.executable))),
            args=["-m", "goldencheetah_mcp.server", "--transport", "stdio"],
            env=env,
            cwd=ROOT,
        )

        gc_home = Path.home() / ".goldencheetah"

        with tempfile.TemporaryDirectory(dir=gc_home) as tmpdir:
            planned_dir = Path(tmpdir) / "planned"
            planned_dir.mkdir()

            activity_data = {
                "workoutPath": "/tmp/mock.erg",
                "date": "2026-04-04",
                "time": "06:00:00",
                "sport": "Bike",
                "title": "Test Ride",
            }
            activity_file = planned_dir / "2026_04_04_06_00_00.json"
            activity_file.write_text(json.dumps(activity_data), encoding="utf-8")

            workout_file = Path(tmpdir) / "test_workout.erg"
            workout_file.write_text("[COURSE HEADER]\n[END COURSE HEADER]\n", encoding="utf-8")

            # Derive a fake athlete name from the tmpdir basename
            # so _resolve_planned_dir won't be used — we pass filepath directly
            async with stdio_client(server) as (read_stream, write_stream):
                session = ClientSession(
                    read_stream,
                    write_stream,
                    read_timeout_seconds=timedelta(seconds=10),
                )
                async with session:
                    await session.initialize()

                    update_result = await session.call_tool(
                        "gc_update_planned_activity",
                        {
                            "athlete": "Test Rider",
                            "filepath": str(activity_file),
                            "confirm": True,
                            "title": "Updated Ride",
                            "time": "08:00:00",
                        },
                    )
                    self.assertTrue(update_result.structuredContent["updated"])
                    self.assertEqual(
                        update_result.structuredContent["activity"]["title"],
                        "Updated Ride",
                    )
                    self.assertEqual(
                        update_result.structuredContent["activity"]["time"],
                        "08:00:00",
                    )

                    delete_plan_result = await session.call_tool(
                        "gc_delete_planned_activity",
                        {
                            "athlete": "Test Rider",
                            "filepath": str(activity_file),
                            "confirm": True,
                        },
                    )
                    self.assertTrue(delete_plan_result.structuredContent["deleted"])
                    self.assertEqual(
                        delete_plan_result.structuredContent["filepath"],
                        str(activity_file),
                    )

                    delete_workout_result = await session.call_tool(
                        "gc_delete_workout",
                        {
                            "athlete": "Test Rider",
                            "filepath": str(workout_file),
                            "confirm": True,
                        },
                    )
                    self.assertTrue(delete_workout_result.structuredContent["deleted"])
                    self.assertFalse(workout_file.exists())

    def test_bom_handling(self) -> None:
        """GoldenCheetah writes JSON with UTF-8 BOM; list and update must handle it."""
        anyio.run(self._exercise_bom_handling)

    async def _exercise_bom_handling(self) -> None:
        env = os.environ.copy()
        env["GC_API_BASE_URL"] = self.base_url

        server = StdioServerParameters(
            command=os.environ.get("PYTHON", str(Path(sys.executable))),
            args=["-m", "goldencheetah_mcp.server", "--transport", "stdio"],
            env=env,
            cwd=ROOT,
        )

        gc_home = Path.home() / ".goldencheetah"

        with tempfile.TemporaryDirectory(dir=gc_home) as tmpdir:
            planned_dir = Path(tmpdir) / "planned"
            planned_dir.mkdir()

            # Write a planned activity file WITH a UTF-8 BOM, mimicking GoldenCheetah
            bom_data = {
                "workoutPath": "/tmp/bom-test.erg",
                "date": "2026-04-05",
                "time": "07:00:00",
                "sport": "Bike",
                "title": "BOM Test Ride",
            }
            bom_file = planned_dir / "2026_04_05_07_00_00.json"
            bom_content = b"\xef\xbb\xbf" + json.dumps(bom_data).encode("utf-8")
            bom_file.write_bytes(bom_content)

            async with stdio_client(server) as (read_stream, write_stream):
                session = ClientSession(
                    read_stream,
                    write_stream,
                    read_timeout_seconds=timedelta(seconds=10),
                )
                async with session:
                    await session.initialize()

                    # gc_list_planned_activities must parse BOM files without error
                    list_result = await session.call_tool(
                        "gc_list_planned_activities",
                        {"athlete": Path(tmpdir).name},
                    )
                    activities = list_result.structuredContent["activities"]
                    self.assertEqual(len(activities), 1)
                    self.assertEqual(activities[0]["title"], "BOM Test Ride")
                    self.assertEqual(activities[0]["_filepath"], str(bom_file))

                    # gc_update_planned_activity must read BOM files and update them
                    update_result = await session.call_tool(
                        "gc_update_planned_activity",
                        {
                            "athlete": Path(tmpdir).name,
                            "filepath": str(bom_file),
                            "confirm": True,
                            "title": "Updated BOM Ride",
                        },
                    )
                    self.assertTrue(update_result.structuredContent["updated"])
                    self.assertEqual(
                        update_result.structuredContent["activity"]["title"],
                        "Updated BOM Ride",
                    )

                    # Verify the updated file is still valid JSON (with or without BOM)
                    updated_content = bom_file.read_text(encoding="utf-8-sig")
                    updated_data = json.loads(updated_content)
                    self.assertEqual(updated_data["title"], "Updated BOM Ride")
