from __future__ import annotations

import json
import os
import sys
import threading
import unittest
from datetime import timedelta
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import anyio
from mcp.client.session import ClientSession
from mcp.client.stdio import StdioServerParameters, stdio_client


ROOT = Path(__file__).resolve().parents[1]


class MockGoldenCheetahHandler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:  # noqa: N802
        if self.path == "/":
            body = "name,dob,weight,height,sex\nTest Rider, 1990/01/01, 72, 180, Male\n"
            self._write(200, body, "text/csv; charset=UTF-8")
            return

        if self.path.startswith("/Test%20Rider/ai/snapshot"):
            body = {
                "snapshot": {
                    "athleteName": "Test Rider",
                    "date": "2026-04-04",
                    "ftp": 250,
                    "cp": 250,
                    "ctl": 65.2,
                    "atl": 70.1,
                    "tsb": -4.9,
                    "canGenerate": True,
                },
                "generatorId": "goldencheetah-heuristic-v1",
                "supportedWorkoutTypes": [
                    "recovery",
                    "endurance",
                    "sweetspot",
                    "threshold",
                    "vo2max",
                    "anaerobic",
                    "mixed",
                ],
            }
            self._write_json(200, body)
            return

        self._write_json(404, {"error": f"Unhandled GET {self.path}"})

    def do_POST(self) -> None:  # noqa: N802
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length)
        payload = json.loads(raw.decode("utf-8"))

        if self.path == "/Test%20Rider/ai/draft":
            body = {
                "snapshot": {
                    "athleteName": "Test Rider",
                    "date": payload.get("date", "2026-04-04") or "2026-04-04",
                    "ftp": 250,
                    "cp": 250,
                    "ctl": 65.2,
                    "atl": 70.1,
                    "tsb": -4.9,
                    "canGenerate": True,
                },
                "draft": {
                    "schemaVersion": "1",
                    "displayName": payload.get("displayName", "AI Threshold 60min") or "AI Threshold 60min",
                    "description": payload.get("description", "Generated by test harness"),
                    "generatorId": payload.get("generatorId", "goldencheetah-mcp"),
                    "modelId": payload.get("modelId", ""),
                    "modelVersion": payload.get("modelVersion", ""),
                    "steps": [
                        {
                            "durationSec": 600,
                            "powerMode": "percentFtp",
                            "powerValue": 60.0,
                            "label": "Warmup",
                        },
                        {
                            "durationSec": 300,
                            "powerMode": "percentFtp",
                            "powerValue": 100.0,
                            "label": "Threshold 1",
                        },
                    ],
                },
                "warnings": [],
            }
            self._write_json(200, body)
            return

        if self.path == "/Test%20Rider/ai/save":
            draft = payload["draft"]
            body = {
                "saved": True,
                "filepath": "/tmp/mock-workout.erg",
                "displayName": draft.get("displayName", ""),
                "generatorId": draft.get("generatorId", ""),
            }
            self._write_json(200, body)
            return

        if self.path == "/Test%20Rider/ai/plan":
            body = {
                "saved": True,
                "filepath": "/tmp/2026_04_04_06_00_00.json",
                "workoutPath": payload["workoutPath"],
                "when": "2026-04-04T06:00:00",
            }
            self._write_json(200, body)
            return

        self._write_json(404, {"error": f"Unhandled POST {self.path}"})

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A003
        return

    def _write_json(self, status: int, payload: dict[str, Any]) -> None:
        self._write(status, json.dumps(payload), "application/json; charset=UTF-8")

    def _write(self, status: int, body: str, content_type: str) -> None:
        data = body.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)


class GoldenCheetahMcpIntegrationTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.httpd = ThreadingHTTPServer(("127.0.0.1", 0), MockGoldenCheetahHandler)
        cls.base_url = f"http://127.0.0.1:{cls.httpd.server_address[1]}"
        cls.thread = threading.Thread(target=cls.httpd.serve_forever, daemon=True)
        cls.thread.start()

    @classmethod
    def tearDownClass(cls) -> None:
        cls.httpd.shutdown()
        cls.thread.join(timeout=5)
        cls.httpd.server_close()

    def test_stdio_tools_round_trip(self) -> None:
        anyio.run(self._exercise_stdio_server)

    async def _exercise_stdio_server(self) -> None:
        env = os.environ.copy()
        env["GC_API_BASE_URL"] = self.base_url

        server = StdioServerParameters(
            command=os.environ.get("PYTHON", str(Path(sys.executable))),
            args=["-m", "goldencheetah_mcp.server", "--transport", "stdio"],
            env=env,
            cwd=ROOT,
        )

        async with stdio_client(server) as (read_stream, write_stream):
            session = ClientSession(
                read_stream,
                write_stream,
                read_timeout_seconds=timedelta(seconds=10),
            )
            async with session:
                await session.initialize()

                tools = await session.list_tools()
                tool_names = {tool.name for tool in tools.tools}
                self.assertIn("gc_list_athletes", tool_names)
                self.assertIn("gc_get_athlete_snapshot", tool_names)
                self.assertIn("gc_create_workout_draft", tool_names)
                self.assertIn("gc_save_workout", tool_names)
                self.assertIn("gc_create_planned_activity", tool_names)

                athletes_result = await session.call_tool("gc_list_athletes")
                athletes = athletes_result.structuredContent["athletes"]
                self.assertEqual(athletes[0]["name"], "Test Rider")

                draft_result = await session.call_tool(
                    "gc_create_workout_draft",
                    {
                        "athlete": "Test Rider",
                        "workout_type": "threshold",
                        "duration_min": 60,
                        "display_name": "Threshold Builder",
                    },
                )
                draft = draft_result.structuredContent["draft"]
                self.assertEqual(draft["displayName"], "Threshold Builder")

                save_result = await session.call_tool(
                    "gc_save_workout",
                    {
                        "athlete": "Test Rider",
                        "draft": draft,
                        "confirm": True,
                    },
                )
                self.assertTrue(save_result.structuredContent["saved"])
                self.assertEqual(save_result.structuredContent["filepath"], "/tmp/mock-workout.erg")

                plan_result = await session.call_tool(
                    "gc_create_planned_activity",
                    {
                        "athlete": "Test Rider",
                        "workout_path": "/tmp/mock-workout.erg",
                        "date": "2026-04-04",
                        "confirm": True,
                    },
                )
                self.assertTrue(plan_result.structuredContent["saved"])
                self.assertEqual(plan_result.structuredContent["filepath"], "/tmp/2026_04_04_06_00_00.json")
